/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.8
 * Generated at: 2014-06-23 05:18:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.grayscale;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- The MIT License (MIT)\r\n");
      out.write("\r\n");
      out.write("Copyright (c) IIIT-DELHI \r\n");
      out.write("authors:\r\n");
      out.write("HEMANT JAIN \"hjcooljohny75@gmail.com\"\r\n");
      out.write("ANIRUDH NAIN \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("Permission is hereby granted, free of charge, to any person obtaining a copy\r\n");
      out.write("of this software and associated documentation files (the \"Software\"), to deal\r\n");
      out.write("in the Software without restriction, including without limitation the rights\r\n");
      out.write("to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\r\n");
      out.write("copies of the Software, and to permit persons to whom the Software is\r\n");
      out.write("furnished to do so, subject to the following conditions:\r\n");
      out.write("\r\n");
      out.write("The above copyright notice and this permission notice shall be included in\r\n");
      out.write("all copies or substantial portions of the Software.\r\n");
      out.write("\r\n");
      out.write("THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\r\n");
      out.write("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\r\n");
      out.write("FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\r\n");
      out.write("AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\r\n");
      out.write("LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\r\n");
      out.write("OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\r\n");
      out.write("THE SOFTWARE. -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Mail Detective</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"ico/E-Mail.ico\">\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Fonts -->\r\n");
      out.write("    <link href=\"http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme CSS -->\r\n");
      out.write("    <link href=\"css/grayscale.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/login.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/circular.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\" data-spy=\"scroll\" data-target=\".navbar-custom\">\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-custom navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"navbar-header page-scroll\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-main-collapse\">\r\n");
      out.write("                    <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#page-top\">\r\n");
      out.write("                    <i class=\"fa fa-play-circle\"></i>  <span class=\"light\">Home</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("            <div class=\"collapse navbar-collapse navbar-right navbar-main-collapse\">\r\n");
      out.write("                <ul class=\"nav navbar-nav\">\r\n");
      out.write("                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->\r\n");
      out.write("                    <li class=\"hidden\">\r\n");
      out.write("                        <a href=\"#page-top\"></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"page-scroll\">\r\n");
      out.write("                        <a href=\"#about\">About</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"page-scroll\">\r\n");
      out.write("                        <a href=\"#developers\">Developers</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"page-scroll\">\r\n");
      out.write("                        <a href=\"#contact\">Contact</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-collapse -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.container -->\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"intro\">\r\n");
      out.write("        <div class=\"intro-body\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-8 col-md-offset-2\">\r\n");
      out.write("                        <h4 class=\"brand-heading\"> Mail Detective</h4>\r\n");
      out.write("                        <div class=\"login\">\r\n");
      out.write("                        <form name=\"myForm\" action=\"NewFile.jsp\" method=\"post\" >\r\n");
      out.write("                        <input type=\"text\" placeholder=\"username\" name=\"user\"><br>\r\n");
      out.write("                        <input type=\"password\" placeholder=\"password\" name=\"password\"><br>\r\n");
      out.write("                        \r\n");
      out.write("                        <a href=\"gmail_like.html\"><input type=\"submit\" value=\"Login\"></a>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <p class=\"intro-text\">A free, premium quality, responsive , reliable Mail Search Platform.</p>\r\n");
      out.write("                        <div class=\"page-scroll\">\r\n");
      out.write("                            <a href=\"#about\" class=\"btn btn-circle\">\r\n");
      out.write("                                <i class=\"fa fa-angle-double-down animated\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"about\" class=\"container content-section text-center\" style=\"height:750px;\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 col-lg-offset-2\">\r\n");
      out.write("                <h2>About Mail Detective</h2>\r\n");
      out.write("                <p>Mail Detective is a seach tool to make your life easier and simpler.No more wasting your time in finding emails ,Mail Detective provides you extensive mail search platform to perform complex queries .</p>\r\n");
      out.write("                <p>It uses Faceted Search with SPARQL to give faster search results when searching E-Mails.</p>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"developers\" class=\"content-section text-center\">\r\n");
      out.write("        <div style=\"height:750px;padding-top:50px;\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"col-lg-8 col-lg-offset-2\">\r\n");
      out.write("                    <h1 style=\"margin-top:-175px\">Developers</h1>\r\n");
      out.write("                  <div class=\"circular\">\r\n");
      out.write("                    <div style=\"padding-top:35px;padding-left:200px;font-size:30px;white-space: nowrap;\">\r\n");
      out.write("                    Anirudh Nain<br>\r\n");
      out.write("                    <p>LNMIIT</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                   <div class=\"circular-1\"></div>\r\n");
      out.write("                    <div style=\"margin-top:-140px;padding-left:700px;font-size:30px;white-space: nowrap;\">\r\n");
      out.write("                    Hemant Jain<br>\r\n");
      out.write("                    <p>LNMIIT</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"contact\" class=\"container content-section text-center\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-8 col-lg-offset-2\">\r\n");
      out.write("                <h2>Contact And Feedback</h2>\r\n");
      out.write("                <p>Feel free to email us to provide some feedback on our WEBAPP, give us suggestions for new features and ideas, or to just say hello!</p>\r\n");
      out.write("                <p>hemantjain.y12@lnmiit.ac.in</p>\r\n");
      out.write("                <ul class=\"list-inline banner-social-buttons\">\r\n");
      out.write("                    <li><a href=\"https://twitter.com/SBootstrap\" class=\"btn btn-default btn-lg\"><i class=\"fa fa-twitter fa-fw\"></i> <span class=\"network-name\">Twitter</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"https://github.com/IronSummitMedia/startbootstrap\" class=\"btn btn-default btn-lg\"><i class=\"fa fa-github fa-fw\"></i> <span class=\"network-name\">Github</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"https://plus.google.com/+Startbootstrap/posts\" class=\"btn btn-default btn-lg\"><i class=\"fa fa-google-plus fa-fw\"></i> <span class=\"network-name\">Google+</span></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"map\"></div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core JavaScript Files -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Maps API Key - You will need to use your own API key to use the map feature -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme JavaScript -->\r\n");
      out.write("    <script src=\"js/grayscale.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
